# Generated by Django 3.2 on 2023-06-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Heraldo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('measurement', models.CharField(choices=[('Kg', 'Kilogram'), ('Lb', 'Pound')], default='Kg', max_length=2)),
                ('color', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
