# Generated by Django 3.2 on 2023-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0002_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
