# Generated by Django 3.2 on 2023-06-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Heraldo', '0004_alter_truck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='user_rol',
            field=models.CharField(choices=[('AD', 'Admin'), ('DR', 'Drive'), ('CL', 'Client'), ('NN', 'None')], default='CL', max_length=2),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('origin_coord_lat', models.CharField(max_length=255)),
                ('origin_coord_long', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('destination_coord_lat', models.CharField(max_length=255)),
                ('destination_coord_long', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PD', 'Pendiente'), ('EP', 'En Proceso'), ('FN', 'Finalizado'), ('CN', 'Cancelado')], default='PD', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Heraldo.driver')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
