# Generated by Django 3.2 on 2023-06-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0006_alter_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Heraldo.truck'),
        ),
    ]
