# Generated by Django 3.2 on 2023-06-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0008_order_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='log',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
