# Generated by Django 3.2 on 2023-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0009_auto_20230624_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_coord_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_coord_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_update',
            field=models.DateField(auto_now=True),
        ),
    ]
