# Generated by Django 3.2 on 2023-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0010_auto_20230624_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
