# Generated by Django 3.2 on 2023-06-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0012_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toneladas_seis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('toneladas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('toneladas_diez', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kilogramos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('libras', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
