# Generated by Django 3.2 on 2023-07-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0016_console_consolepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Heraldo.console')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Heraldo.order')),
            ],
        ),
    ]
