# Generated by Django 3.2 on 2023-07-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0017_ordersfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
