# Generated by Django 3.2 on 2023-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0018_order_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='color_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, default='Disponible', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='measurement',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('Lb', 'Pound'), ('Tn', 'Toneladas')], default='Kg', max_length=2),
        ),
    ]
