# Generated by Django 3.2 on 2023-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0019_auto_20230702_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
