# Generated by Django 3.2 on 2023-07-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0022_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='user',
        ),
    ]
