# Generated by Django 3.2 on 2023-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0023_remove_formulario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='tipo',
            field=models.CharField(choices=[('Imprevisto', 'Reporte de Imprevisto'), ('Confirmacion', 'Confirmacion de entrega')], default='Confirmacion', max_length=12),
        ),
    ]
