# Generated by Django 3.2 on 2023-07-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0024_formulario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Heraldo.console'),
        ),
    ]
