# Generated by Django 3.2 on 2023-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0027_auto_20230903_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True),
        ),
    ]
