# Generated by Django 3.2 on 2023-10-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0028_alter_order_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tiempo_partida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
