# Generated by Django 3.2 on 2023-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0034_auto_20231019_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tiempo_partida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
