# Generated by Django 3.2 on 2023-10-20 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heraldo', '0036_auto_20231019_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tiempo_partida',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
